name: Compile sing-box rule-sets ðŸ”¥

on:
  push:
    paths:
      - 'list.txt'
      - 'proxy.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sing-box
        run: |
          curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.8.10/sing-box-1.8.10-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          mv sing-box-*/sing-box .
          chmod +x sing-box

      - name: Compile Blocklist ðŸ› 
        run: |
          echo '{"version": 1, "rules": [{"domain": [' > block.json
          sed 's/^/"/;s/$/",/' list.txt | sed '$ s/,$//' >> block.json
          echo ']}]}' >> block.json
          ./sing-box rule-set compile --output rules.srs block.json

      - name: Compile Proxylist ðŸ› 
        run: |
          echo '{"version": 1, "rules": [{"domain": [' > proxy.json
          sed 's/^/"/;s/$/",/' proxy.txt | sed '$ s/,$//' >> proxy.json
          echo ']}]}' >> proxy.json
          ./sing-box rule-set compile --output proxy.srs proxy.json

      - name: Push results ðŸš€
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add rules.srs proxy.srs
          git commit -m "Update binary rules: $(date)" || exit 0
          git push
