name: Compile sing-box rule-sets üî•

on:
  push:
    paths:
      - 'block.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sing-box
        run: |
          curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.8.10/sing-box-1.8.10-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          mv sing-box-*/sing-box .
          chmod +x sing-box

      - name: Compile Blocklist üõ†
        run: |
          # –§–æ—Ä–º–∏—Ä—É–µ–º JSON –∏–∑ block.txt
          echo '{"version": 1, "rules": [{"domain": [' > block.json
          sed 's/^/"/;s/$/",/' block.txt | sed '$ s/,$//' >> block.json
          echo ']}]}' >> block.json
          
          # –ö–æ–º–ø–∏–ª—è—Ü–∏—è –≤ –±–∏–Ω–∞—Ä–Ω—ã–π —Ñ–æ—Ä–º–∞—Ç .srs
          ./sing-box rule-set compile --output block.srs block.json

      - name: Push results üöÄ
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add block.srs
          git commit -m "Update binary blocklist: $(date)" || exit 0
          git push
